### ISSUE TITLE
Build error with latest `rolldown`/`tsdown`

### ISSUE THREAD

**Issue by sondr3** [sxzz/rolldown-plugin-dts#90]
### Describe the bug

I just upgraded to `rolldown@1.0.0-beta.34`, `rolldown-plugin-dts@0.15.8` and `tsdown@0.14.2`, and now suddenly get a 

```
@fm/api-client:build: ℹ Using tsdown config: ~/repo/packages/api-client/tsdown.config.ts
@fm/api-client:build: ℹ entry: src/index.ts
@fm/api-client:build: ℹ tsconfig: tsconfig.json
@fm/api-client:build: ℹ Build start
@aritma/css:build: Built 32 CSS files
@fm/api-client:build: 
@fm/api-client:build:  ERROR  Error: Build failed with 1 error:
@fm/api-client:build: 
@fm/api-client:build: [plugin rolldown-plugin-dts:generate]
@fm/api-client:build: RollupError: src/client.ts(3,50): error TS6307: File '~/repo/packages/api-client/src/__generated__/arm.ts' is not listed within the file list of project '~/repo/packages/api-client/tsconfig.json'. Projects must list all files or use an 'include' pattern.
@fm/api-client:build:   File is ECMAScript module because '~/repo/packages/api-client/package.json' has field "type" with value "module"
@fm/api-client:build: src/client.ts(12,30): error TS6307: File '~/repo/packages/api-client/src/utils.ts' is not listed within the file list of project '~/repo/packages/api-client/tsconfig.json'. Projects must list all files or use an 'include' pattern.
```

error, but this worked using `rolldown@1.0.0-beta.32`, `rolldown-plugin-dts@0.15.6` and `tsdown@0.14.0`

### Reproduction

https://github.com/sondr3/rolldown-plugin-dts-repro

### System Info

```Shell
System:
    OS: macOS 15.5
    CPU: (14) arm64 Apple M4 Pro
    Memory: 68.91 MB / 48.00 GB
    Shell: 4.0.2 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.18.0 - ~/code/projects/aritma/FinanceManager/frontend/node_modules/.bin/node
    npm: 10.9.2 - ~/.local/share/mise/installs/node/22.17.1/bin/npm
    pnpm: 10.15.0 - ~/.local/share/mise/installs/node/22.17.1/bin/pnpm
  Browsers:
    Edge: 138.0.3351.121
    Safari: 18.5
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by sxzz** [comment]
Without a minimal reproduction, we’re unable to determine what happened.

> [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by sxzz** [comment]
At the very least, you can test each commit individually and let us know which one is causing the issue.

https://github.com/sxzz/rolldown-plugin-dts/runs/48544117110

**Comment by sondr3** [comment]
I've added a minimal repro here: https://github.com/sondr3/rolldown-plugin-dts-repro. Installing and running `pnpm build` will result in a crash.
